config/routes.rb
Hactavism::Application.routes.draw do
  resources :links

  root :to => "links#root"

  match "/auth/twitter/callback" => "sessions#create", via: [:get, :post]
 
  get 'hactavists' => 'links#hactavists'

  get 'links/:id/upvote'  => 'links#upvote', as: "upvote"
  get 'links/:id/downvote'  => 'links#downvote', as: "downvote"

end

app/models/link.rb
class Link < ActiveRecord::Base

  include ActiveModel::Validations
  validates_with VideoValidator
  validates_presence_of :tags, :length => { :minimum => 3 }

  def youtube_embed(youtube_url)
    if youtube_url[/yout\.be\/([^\?]*)/]
      youtube_id = $1
    else
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end
    %Q{<iframe title="youTube video player" width="800" height="487.5" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end

  def vimeo_embed(vimeo_url)
    vimeo_id = vimeo_url[-8..-1]
    %Q{<iframe id="moog" src="http://player.vimeo.com/video/#{ vimeo_id }" width="800" height="487.5" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>} 
  end

  def embed(url)
    if url.include?("youtube")
      youtube_embed(url)
    elsif url.include?("vimeo")
      vimeo_embed(url)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.create_with_omniauth(auth)
		create! do |user|
			user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
		end
	end
end

app/models/video_validator.rb
class VideoValidator < ActiveModel::Validator

  def validate(record)
    unless valid_url?(record.content)
      record.errors[:content] << "Sorry - Only YouTube or Vimeo URL's are allowed"
    end
  end

  YOUTUBE_REGEXP = /^(?:http:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/
  VIMEO_REGEXP = /^(?:http:\/\/)?(?:www\.)?vimeo\.com\/\d{6,8}(?=\b|\/)/  

  def valid_url?(url)
    !!(YOUTUBE_REGEXP =~ url) | !!(VIMEO_REGEXP =~ url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.order('created_at DESC').page(params[:page]).per(12)
  end

  class VolunteerOption
    def initialize(name,url)
      @name = name
      @url = url
    end

    attr_accessor :name, :url
  end

  def show
    @link = Link.find(params[:id])
    @tags = @link.tags.gsub(' ', '+').gsub(',', '')

    @tweet_text = URI.escape "#{@link.title} => #{@link.content}via #{@Nomadic_Knight}"
    
    # @volunteer_ops = Volunteer.opportunities(@tags)

    @url = "http://api.charitynavigator.org/api/v1/search/?app_key=#{ENV['CHARITY_NAVIGATOR_KEY']}&app_id=#{ENV['CHARITY_NAVIGATOR_APP_ID']}&format=json&term=#{@tags}"
  end

  def root
    @link = Link.last
  end

  def new
    @link = Link.new
  end

  def edit
  end

  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:content, :tags, :description, :title, :points, :score)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		auth = request.env["omniauth.auth"]
		user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
		session[:user_id] = user.id
		redirect_to root_url, notice: "Signed In"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacktivism</title>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Share+Tech+Mono' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Source+Code+Pro:400,600' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="containter">
        <a class="btn btn-navbar" data-toggle="collapse"
          data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Watch Documentaries", links_path, :class => "font" %></li>
            <li><%= link_to "Submit Content", new_link_path, :class => "font" %></li>
            <li><%= link_to "Hacktivists", hactavists_path, :class => "font" %></li>
            <li><%= link_to "Twitter Login", "/auth/twitter", :class => "font" %></li>
            <a class="brand" href="/">Hacktivism<%= image_tag "video.png", :size => '33x33', :class => "video" %></a>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<%= yield %>
  <script type="text/javascript">
    var disqus_shortname = 'SerKnight';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
  </script> 
</body>
</html>

app/views/links/_form.html.erb
<div class="container">
  <div class="row">
    <div class="span8">
      <%= form_for @link, :html => { :class => 'form-horizontal' } do |f| %>
        <div class="control-group">
          <%= f.label "Title", :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :title, :class => 'text_field', :placeholder => "Student Activism is Dying" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label "Video Url", :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :content, :class => 'text_field', :placeholder => "Ex. http://www.youtube.com/watch?v=S4JSeQESzKE" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :tags, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :tags, :class => 'text_field', :placeholder => "Ex. students, activism" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label "Video Description", :class => 'control-label' %>
          <div class="controls">
            <%= f.text_area :description, :class => 'text_field', "placeholder" => "Student activism seems to be at an all time low in America. The Occupy Colleges movement continues..." %>
          </div>
        </div>
      </br>
        <div class="form-actions">
          <%= f.submit "Take Action", :class => 'btn btn-cancel' %>
          <%= link_to "Cancel", links_path, :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <div class="span4" id="guidelines">
      <h4>Guidelines for Posting</h4>
      <ul>
        <li> Only valid YouTube or Vimeo video links</li>
            <ul>
            <li>Use the browser url</li>
            <li>No https: or embedding formats</li>
          </ul>
          <li> Content should promote some type of social, political, economic, or environmental change</li>
            <li> Tags should be simple, yet unique for the content</li>
              <li> Be the change you want to see in the world</li>
        <hr/>
      </ul>
    </div>
  </div>
</div>

app/views/links/hactavists.html.erb
<body>
<div class="container">
  <!-- Main hero unit for a primary marketing message or call to action -->
  <div class="hero-unit">
        <div class="name">
          <h3 class="name">Christopher Knight</h3>
          <h4 class="black"><strong>@Nomadic_Knight</strong></h4>
          <ul>
            <li><a href="https://github.com/SerKnight", style="color: #CC0000", target="_blank">Github</a>  
             <li><a href="http://www.linkedin.com/profile/view?id=73950402&trk=hb_tab_pro_top", style="color: #CC0000", target="_blank">LinkedIn</a>  
              <li><a href="http://www.youtube.com/user/EditApartMentality", style="color: #CC0000", target="_blank">YouTube</a>   
        </div>
    <h3>I'm a Rails developer</h3>
      <ul><strong>Looking for work in</strong></ul>
        <li>Denver</li>
        <li>Seattle, Portland</li>
        <li>Austin</li>
        <li>Los Angeles, San Francisco</li>  
    <div class="toph">
      <%= image_tag "toph.jpg" %>
    </div>
  </div>
  <!-- Example row of columns -->
  <div class="row">
    <div class="span6">
      <hr>
      <h2>Web Development</h2>
      <p>I'm a student in a 6-month intensive Ruby on Rails course in Denver Colorado => <a href="http://www.gschool.it/", style="color: #CC0000">gSchool</a><br> I am focusing on learning Ruby, Rails, HTML5/CSS, jQuery, with an emphasis on agile development and big teams to deliver MVP's and polished applications.</p><hr/>
      I am looking for a place to work with a skilled team of developers in a culture that promotes constant learning. I am a 'junior' dev as many people call it, but I have the motivation and aptitude to really contribute to a full-stack team.<hr/>
      <p>I have been tracking my web-development from the ground up and if you are considering getting into the field - here is a taste of what it feels like to be in <a href="http://serknight.herokuapp.com/", target="_blank", style="color: #CC0000"> Code boot camp</a>.
    </div>
    <div class="span9">
     <hr/>
      <h2>Travel and Film</h2>
       <p>Before setting off on a web-dev career path I had a adventure travel video blog at <a href="http://www.nomadicknight.com", target="_blank", style="color: #CC0000">Nomadic Knight dot com</a>. Being able to travel extensively when I was young really opened my eyes to the realities of our world, and my ultimate goal as a web developer involves being able to help individuals and businesses solve their problems with creative software.</p>
     </br>
   </div>
   <div class="span4">
    <p><%= image_tag "internet.png", :class => "world" %></p>
    <hr/><br><hr/>
   </div>
   <div class="span7", id="projects">
      <hr>
    <h2>Previous Projects</h2>
      <p>Throughout gSchool there has been a large focus on working with teams in an agile process. <br/>Some of our most recent projects have included integrating with multiple API's and creating a multi-tenant e-commerce website capable of holding 10,000 products.</p>
      <h4><a href="http://streamrolled.com", target="_blank", style="color: #CC0000">StreamRolled</a></h4> Is an application that integrates with LastFm & Soundcloud accounts to aggregate musical habits in a very visually appealing grid, much like the 'Pintrest' style. 
       <p><%= link_to( image_tag("streamrolled.png", :class => "streamrolled"), "http://streamrolled.com", :target => "_blank") %></p>
   </div>
   <div class="span4", id="projects2">
      <p><%= link_to( image_tag("obie.png", :class => "store", size: "800x800"), "http://obigear.herokuapp.com", :target => '_blank') %></p>
      <h4><a href="http://obigear.herokuapp.com/", target="_blank", style="color: #CC0000">E-Commerce</a></h4>
      <p>This e-commerce application was built over multiple iterations and ultimately became a multi-tenant e-commerce provider much like Shopify. We built our authentication from scratch while implementing multi-store cart features and an intuitive admin dashboard for each storefront.</p>
   </div>
   <div class="span8">
      <p><%= link_to(image_tag("obigear.png", :class => "tent", :size => "800x800"),"http://obigear.herokuapp.com", :target => "_blank") %></p>
    </div>
  </div>
</div> <!-- /container -->

</body>
<hr>
<br><br>
</html>

app/views/links/index.html.erb
<div class="container">
  <div class="row">
    <div class="span9">
      <div class="index-header">
        <%= link_to "Submit New Film", new_link_path, :id => "new-button",  :class => 'btn btn-cancel' %>
        <h2 class="docs"> Documentary Collection </h2>
      </div>
      <table class="table table-striped" id="documentaries">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Tags</th>
          </tr>
        </thead>
        <tbody>
          <% @links.each do |link| %>
            <tr data-title="<%= link.title %>">
              <td><h5><%= link_to link.title, link_path(link) %></h5></td>
              <td><%= link_to link.description, link_path(link) %></td>
              <td><%= link.tags %></td>
              <td>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
        <%= paginate @links %>
    </div>
    <div class="span3", id="side-pic">
        <%= image_tag('hacker.jpg', :size => "500x500")%>
        <%= image_tag('internet.png', :size => "500x500")%>
        <%= image_tag('hacker.jpg', :size => "500x500")%>
        <%= image_tag('internet.png', :size => "500x500")%>
        <%= image_tag('hacker.jpg', :size => "500x500")%>
        <%= image_tag('internet.png', :size => "500x500")%>
    </div>
  </div>
</div>

app/views/links/new.html.erb
<%- model_class = Link -%>
<div class="page-header">
  <h1><%="Activate a New Video" %></h1>
</div>
<%= render :partial => 'form' %>

app/views/links/root.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="root-header">
        <h2> Online Documentaries to Inspire Action</h2>
      </div>
    </div>
    <div class="span9">
        <h4><%= link_to @link.title.capitalize, links_path, { :class=>"home-link" } %></h4>
       <%= raw(@link.embed(@link.content)) %>
    </div>
    <div class="span3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>What is Hacktivism</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td>Hactivism is the use of internet technology to promote free speech, human rights, and information ethics. <hr/> You will find inspiring videos that will connect you with outlets for action and activism.</td>
              </td>
            </tr>
        </tbody>
      </table>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>What you can do here</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td>
                <ol>
                  <li> You can watch the user submitted content <%= link_to "here", links_path, :style => 'color: red' %>. 
                      <li> You can submit meaningful content to the video collection <%= link_to "here", new_link_path, :style => 'color: red'  %>
                      <li> You can promote action via the charity & volunteer opportunities displayed by each video.</ol>
                      <hr/> 
                  </td>
              </td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/links/show.html.erb
<!DOCTYPE html>
<div class="container">
  <div class="row">
    <div class="span9">
        <%= link_to "Back", links_path, :class => 'btn', :id => "back-button"  %>
      <div class="doc-title">
        <h2><%= "#{@link.title}" %></h2>
      </div>
        <body>
          <a id="facebook-share" href="https://www.facebook.com/sharer/sharer.php?u='<%= @link.content %>')"><%= image_tag "facebook.png" %></a>

          <a id="twitter-share" class="twitter-share-button" href="https://twitter.com/share?url="><%= image_tag "twitter.png" %></a>

          <a id="reddit-share" class="reddit-share-button" href="http://www.reddit.com/submit?url="><%= image_tag "reddit.png" %></a>

          <p><%= raw(@link.embed(@link.content)) %></p>

        <dl class="dl-horizontal">
          <dt><strong>Content:</strong></dt>
          <dd><%= @link.content %></dd>
          <dt><strong>Tags:</strong></dt>
          <dd><%= @link.tags %></dd>
        </dl>

         <%= javascript_include_tag "main/link/show" %>
         <script type="text/javascript">
          hacktavism.Views.show.initialize("<%= @url %>");
         </script>
         <div id="disqus_thread"></div>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>
    <div class="span1">
    <!-- upvotes -->
    </div>
    <div class="span3">
      <li><h3>Video Description</h3>
      <%= @link.description %>
      <li><h3>Volunteer Options</h3>
        
        </dl>
      <li><h3>Related Charities</h3>
      <ul><span class="charity"></span>
        <h4>Cause</h4>
          <span class="cause"></span>
        </ul>
        <hr>  
      </span>
    </div>
  </div>
</div>